### PR TITLE
doc: fix arch.md content 

### PR DESCRIPTION
**Pull request by 3mard**
The link in the docs seems to be broken

### CODE REVIEW

**Comment by zenhack** [comment]
@3mard, it's working for me: https://perkeep.org/doc/terms

**Comment by 3mard** [comment]
Hi @zenhack  
I was viewing the docs through github https://github.com/perkeep/perkeep/blob/master/doc/arch.md
and there the link is broken (https://github.com/perkeep/perkeep/blob/master/doc/terms)

Maybe I am not supposed to view them through github ?

**Comment by zenhack** [comment]
I think the links are written for the rendered site. It's a little weird
to have `.md` in the URL for a page that's not actually markdown (though
`/doc/terms.md` appears to redirect to `/doc/terms` on the live site, so
it still works at least). I'll defer to the actual maintainers (I'm just
a community member) but my take would be to leave it as-is.

Quoting Omer Davutoglu (2020-03-10 14:37:43)

**Comment by mpl** [comment]
> I think the links are written for the rendered site. It's a little weird to have `.md` in the URL for a page that's not actually markdown (though `/doc/terms.md` appears to redirect to `/doc/terms` on the live site, so it still works at least). I'll defer to the actual maintainers (I'm just a community member) but my take would be to leave it as-is. Quoting Omer Davutoglu (2020-03-10 14:37:43)

Yeah we have silly rules in the website for when/where we use .md or not, and I can never remember why and what they are. But given that most of the links in the files in doc/ seem to be .md, I think it's supposed to be that way, so I would not touch it.

**Comment by zenhack** [comment]
Quoting mpl (2020-03-11 05:37:44)

>      I think the links are written for the rendered site. It's a little
>      weird to have .md in the URL for a page that's not actually markdown
>      (though /doc/terms.md appears to redirect to /doc/terms on the live
>      site, so it still works at least). I'll defer to the actual
>      maintainers (I'm just a community member) but my take would be to
>      leave it as-is. Quoting Omer Davutoglu (2020-03-10 14:37:43)
>
>    Yeah we have silly rules in the website for when/where we use .md or
>    not, and I can never remember why and what they are. But given that
>    most of the links in the files in doc/ seem to be .md, I think it's
>    supposed to be that way, so I would not touch it.

The patch *adds* a suffix, not removes one. So perhaps you do want to
merge this?

**Comment by mpl** [comment]
> Quoting mpl (2020-03-11 05:37:44)
> I think the links are written for the rendered site. It's a little weird to have .md in the URL for a page that's not actually markdown (though /doc/terms.md appears to redirect to /doc/terms on the live site, so it still works at least). I'll defer to the actual maintainers (I'm just a community member) but my take would be to leave it as-is. Quoting Omer Davutoglu (2020-03-10 14:37:43) Yeah we have silly rules in the website for when/where we use .md or not, and I can never remember why and what they are. But given that most of the links in the files in doc/ seem to be .md, I think it's supposed to be that way, so I would not touch it.
> The patch *adds* a suffix, not removes one. So perhaps you do want to merge this?

Oh good point, thanks. yeah.

**Comment by willnorris** [comment]
@mpl that silly reason is partially my fault 😕 and is related to #1146

**Comment by mpl** [comment]
@willnorris Ah I knew it was somewhat documented somewhere but could not remember where, sorry (and thanks). No objection to that PR then, right?

**Comment by willnorris** [comment]
I think it might be further documented somewhere else as well, but I'm not finding it right now.  I should still go back and resolve that issue at some point!

And no, of course no objection to the PR :)

**Comment by catrina4200** [comment]
> The link in the docs seems to be broken

3mard:fix-docs-links

**Comment by catrina4200** [comment]
> The link in the docs seems to be broken



> The link in the docs seems to be broken
doc/arch.md

**Pull request merged**
