### PR TITLE
android: return to the android playstore

### LINKED ISSUE #1596: The Perkeep Android app is missing from the Google Play Store
The download link on the website is broken. The app is missing from the store. The alternate version linked on the website appears to be an older version (even uses the older Camlistore name and branding).

### PR DESCRIPTION
**Pull request by MichaHoffmann**
Fixes #1596 #1582 

This PR intends to make the app viable for the android playstore again

* Intents need to get the flag PendingIntent.FLAG_IMMUTABLE/MUTABLE
* Assets are no longer executable, get around that by using
  'extractNativeLibs=true' and executing from the lib path
* Apply several refactoring suggestions by Android Studio
* Rework resources Makefile
* Sideload `pk-put` as a native lib [very hacky]
* rename Camlistore to Perkeep where appropriate

### CODE REVIEW

**Comment by MichaHoffmann** [comment]
Should we also use the opportunity to rename it to perkeep in this PR?

**Comment by MichaHoffmann** [comment]
> Should we also use the opportunity to rename it to perkeep in this PR?

ok i just went ahead and renamed it; PR can be reverted if its problematic.

**Comment by MichaHoffmann** [comment]
FileWatcher seems to be broken, at least i dont register updates when a photo is taken, ill debug that soon

**Comment by mhoffm-aiven** [comment]
Automatic Fileupload now works again ( on my machine ). There was a race condition between inotify and android being able to find the file; a few retries fixed that.

**Review by bradfitz — APPROVED** [review]

**Comment by MichaHoffmann** [comment]
Closed in favor of #1611

**Pull request closed without merging**
