### PR TITLE
upgrade go 1.19 and support editors

### PR DESCRIPTION
**Pull request by kuchaguangjie**
1. upgrade to go **1.19**;
2. update `.gitgnore` to support `goland` and `vscode`;

### CODE REVIEW

**Comment by MichaHoffmann** [comment]
lgtm

**Comment by bradfitz** [comment]
This should update the GitHub Actions go versions too.

**Comment by kuchaguangjie** [comment]
go versions updated in  github actions.

**Comment by MichaHoffmann** [comment]
go 1.19 included `go fmt` changes for doc comments. Probably the code base needs a `go fmt ./...`, that should fix the linter issue.

**Comment by kuchaguangjie** [comment]
The change is huge, probably u should reject this PR, and do it yourself, since the modification itself is very tiny.

**Pull request closed without merging**
