### PR TITLE
app/hello: staticcheck

### PR DESCRIPTION
**Pull request by tgulacsi**

### CODE REVIEW

**Comment by aviau** [comment]
thats a lot of PRs haha...

This one is empty.

What is the first PR?

**Comment by tgulacsi** [comment]
I've closed the empty ones.

**Comment by aviau** [comment]
Both  the extremely big PR and the 100+ you just opened feel extreme. Is there a middle ground?

Can you open them slowly instead of flooding the repository?

The first step would be to setup the configuration for the linter, and have it run in CI, can we do that? Is there a PR that does that? I am not going to look at the 100+ PRs to find the right one.

**Comment by tgulacsi** [comment]
You should've started.

These were quite innocent changes: staticcheck (staticcheck.io) + ineffassign + prealloc + wastedassign.

99.9% just stylistic, the remaining .1% are errors (shadowing, not checked errors).

These were a few days work, but I won't bombard you again.

**Comment by tgulacsi** [comment]
@aviau what about staticcheck, ignoring ST1003,ST1005 ?

    staticcheck -checks $(staticcheck -list-checks|awk '{print $1}'|grep -v ST100[35]|tr '\n' ',') ./...

that's only 270.

What I'd really love, is to delete all those unused code (U1000).

Shall I try a separate PR for each linter/checker?

**Comment by aviau** [comment]
I think any small step is a good thing, I am not against any check in particular.

Can we start with just the unused code one?

**Comment by aviau** [comment]
> Shall I try a separate PR for each linter/checker?

That would be good. But can you open just one to get started?

**Pull request closed without merging**
