### PR TITLE
Ensure make.go prints actual incompatible version

### PR DESCRIPTION
**Pull request by tekknolagi**
Previously it printed the ASCII character corresponding to the decimal value

### CODE REVIEW

**Comment by mpl** [comment]
Hello.

Thank you, but we do not accept github PRs.
Do you want to submit a CL yourself (see https://perkeep.org/code#contributing) ? Or do you want me to do it for you (ill set you as the author of the commit) ?

**Comment by tekknolagi** [comment]
Hi @mpl -- sorry for not reading the website! My bad.

If you could do it for me, that would be great. If that's a bother, I can figure out Gerrit this weekend. Cheers!

**Comment by mpl** [comment]
Done: https://camlistore-review.googlesource.com/c/camlistore/+/14487 , but I'll need a real address email for the commit, and you'll need to sign the CLA before we can merge the change.

**Comment by tekknolagi** [comment]
My email address is tekknolagi@gmail.com and sure, I'll check out the CLA

**Comment by tekknolagi** [comment]
Where can I find it?

**Comment by mpl** [comment]
As specified on https://perkeep.org/code#contributing , https://cla.developers.google.com/ :-)

**Comment by tekknolagi** [comment]
Done!

**Comment by mpl** [comment]
and done! thank you.

**Comment by tekknolagi** [comment]
Neat :D

**Pull request closed without merging**
