### PR TITLE
doc: document all environement variables

### LINKED ISSUE #486: New environment vars are undocumented
<pre>$ go run dev/envvardoc/envvardoc.go 
Undocumented                  Location
CAMLI_API_HOST                pkg/app/app.go:35
CAMLI_APP_BACKEND_URL         pkg/app/app.go:58
CAMLI_PICASA_FULL_IMPORT      pkg/importer/picasa/picasa.go:150
CAMLI_REINDEX_START           pkg/index/index.go:221
CAMLI_S3_TEST_CONFIG_JSON     pkg/blobserver/s3/s3_test.go:29
CAMLI_SERVER                  pkg/client/config.go:255
CAMLI_SYNC_VALIDATE           pkg/server/sync.go:116
CAMLI_TWITTER_FULL_IMPORT     pkg/importer/twitter/twitter.go:159
CAMLI_TWITTER_SKIP_API_IMPORT pkg/importer/twitter/twitter.go:197

It would be nice to get these added to doc/environment-vars.txt</pre>

### PR DESCRIPTION
**Pull request by aviau**
closes #486   (in a reasonable way -- list all vars but not all of them are documented exhaustively)

    doc: document all environement variables
    
    envvardoc: repair the script so that it does not fail on very long
    lines.
    
    envvardoc: look for env vars with the `PERKEEP` prefix too.
    
    envvardoc: adapt the `docVar` regex to the markdown format.
    
    envvardoc: also look for vars in internal/.
    
    CI: run envvardoc so that we notice when we add new undocumented
    environement variables.
    
    doc: List all remaining undocumented env variables. This "shitlist"
    gives us a green build in the CI and allows us to ensure all new
    environment variables are documented in the future.
    
    doc: Link to the environment variables page.

### CODE REVIEW

**Comment by aviau** [comment]
cc @bradfitz for review!

**Comment by mikefaille** [comment]
We could also add this variable on this PR : `CAMLI_CONFIG_DIR`
It's related to this issue : https://github.com/perkeep/perkeep/issues/1389

**Comment by aviau** [comment]
> We could also add this variable on this PR : CAMLI_CONFIG_DIR

Its already there.

**Comment by mikefaille** [comment]
Oh, I see, we must refer this page from somewhere then.  If I do the following command `grep -R environment-vars`, I can see there is no reference on this documentation from the website.

**Comment by aviau** [comment]
> we must refer this page from somewhere then

This PR already does exactly this. (see the commit message and the change to `doc/README.md`)

**Pull request merged**
