### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by tgulacsi**
Update all dependencies (most are at least 2 years old).

### CODE REVIEW

**Comment by aviau** [comment]
I'll gladly merge this as soon as the macos tests pass.

**Comment by tgulacsi** [comment]
How can I test on macos, without such a machine?

**Comment by tgulacsi** [comment]
With a freshly compiled darling (github.com/darlinghq/darling), it passes:

```
Darling [/Volumes/SystemRoot/tmp]$ ./search.test -test.run=Alloc -test.v
=== RUN   TestGetPermanodeLocationAllocs
    handler_test.go:1020: explicit location from attrs: 0 allocations (max 0)
    handler_test.go:1020: referenced permanode location: 1 allocations (max 1)
    handler_test.go:1020: location from exif photo: 1 allocations (max 1)
--- PASS: TestGetPermanodeLocationAllocs (0.52s)
PASS
```

So, I don't know what happens in GitHub's test machine.

**Comment by aviau** [comment]
Maybe try disabling cache in the macos build? I've had similar issues in the past. We can remove cache from the macos workflow and never put it back...

**Comment by tgulacsi** [comment]
How can I remove the cache?

**Comment by aviau** [comment]
By removing these lines:

https://github.com/perkeep/perkeep/blob/8171ea5b511bb969590f4439b8726b9e76c6499a/.github/workflows/tests-macos.yml#L18-L22

**Comment by aviau** [comment]
I know this sucks but the other option for debugging this quickly without access to macos would be to update ~50% of the libs and see if the build passes, then the other 50%.

You can test multiple setups in parallel by pushing to different branches and github will build them all in parallel.

**Comment by aviau** [comment]
This looks good to me @tgulacsi.

Are you done? I can merge whenever.

**Comment by tgulacsi** [comment]
Yes, I am. Please merge it.

**Comment by aviau** [comment]
Done! thanks :))

**Pull request merged**
