### PR TITLE
internal/rollsum: replace with go4.org/rollsum

### LINKED ISSUE #1249: rollsum: use go4 rollsum package instead
I went to use the rollsum package again, and was sad to find that it had been made internal. It's a useful utility package. Can I convince you to make it public for the greater good? Or maybe even move it to go4 or some standalone home?

### PR DESCRIPTION
**Pull request by josharian**
Fixes #1249

Change-Id: Ia88ff8a3711ff0658f557b027c08d3fae1a92ee5

### CODE REVIEW

**Comment by mpl** [comment]
Whoops, I didn't tell you in the issue, because I thought you knew: we use gerrit for contributions, not github. https://perkeep.org/code#contributing

**Comment by josharian** [comment]
OK. I think I've just about exceeded the time I can allot to this. (I love gerrit; I'm happy about that.) This patch is trivial; just some deleted code and updated import paths. Can I let you do it, perhaps?

**Comment by mpl** [comment]
yeah we'll do it, no worries. thanks.

**Comment by mpl** [comment]
https://perkeep-review.googlesource.com/c/perkeep/+/18986

**Comment by josharian** [comment]
Thanks!

**Pull request closed without merging**
